# Generated by Django 5.2.1 on 2025-09-17 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('show_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TheaterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('reserved_seats', models.IntegerField()),
                ('unreserved_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reserved_seats', models.IntegerField()),
                ('amount', models.IntegerField(default=0)),
                ('show_details', models.ForeignKey(db_column='show_details_id', on_delete=django.db.models.deletion.CASCADE, to='showbox.showdetails')),
                ('theater_details', models.ForeignKey(db_column='theater_details_id', on_delete=django.db.models.deletion.CASCADE, to='showbox.theaterdetails')),
            ],
        ),
    ]
